### PR TITLE
Bump plugins and dependencies.

### PR DESCRIPTION
**Pull request by guidomedina**
Bump plugins and dependencies, the following are the most relevant:
- Netty to 4.0.38.Final
- Jackson to 2.8.0
- Slf4j to 1.7.21
- Jinterface to 1.6.1

It all compiles and all tests ran locally passed.

### CODE REVIEW

**Comment by guidomedina** [comment]
- Riak Java Client version: **2.0.6**
- Java version: **1.8**
- Riak version: **2.1.4**
- Operating System / Distribution & Version: **Ubuntu 14.04 Server LTS**
- Riak's `error.log` file, if applicable: **N/A**
- What methods were being executed during the error: **N/A**
- What you _expected_ to have happen: **Nothing really, I used to contribute to Riak 1.x a couple of years ago, warming up again with this easy PR which should be harmless and benefitial.**
- Sample data, if applicable: **N/A**

**Comment by alexmoore** [comment]
Hey @guidomedina,
Thanks for the PR!  

I'll take a look at the changes for each lib update.  We've been bitten before by upgrading (https://github.com/basho/riak-java-client/issues/619), so I'll need to see if anything breaks - hopefully it doesn't. 

Thanks,
Alex

**Comment by guidomedina** [comment]
@alexmoore have you tested the Riak Java client with Netty 4.1.x?

At the moment we use another framework that we can't upgrade because of compatibility issues between Netty 4.0.x and 4.1.x so I was wondering if Riak Java client have been tested with Netty 4.1.x

In the meantime I will test on my side and maybe _-because this PR has been postponed for 2.1.x-_ re-push with Netty 4.1.x if it works for me.

**Comment by guidomedina** [comment]
@alexmoore I have added one more commit with Netty migration to 4.1.x including a deprecated API use fixed.

I will do some more tests here and if it works we would build an internal version with it, you can always cherry pick the first commit if the 2nd isn't aligned with Riak Java client's moving forward plan.

**Edit:** It seems to work fine with Netty 4.1.2.Final

**Comment by guidomedina** [comment]
Updated to 4.1.3.Final and force pushed.

**Comment by alexmoore** [comment]
+1

**Pull request merged**
