### PR TITLE
Add timeout-constrained version of execute on RiakClient

### PR DESCRIPTION
**Pull request by alexmoore**
This supersedes PR #610 (CLIENTS-922), by adding tests to the original PR.

### CODE REVIEW

**Comment by alexmoore** [comment]
Special thanks to @bwittwer for the original PR!

**Comment by lukebakken** [comment]
@alexmoore please to be fixing your builds :-P

```
[WARNING] /home/buildbot/masters/riak/java-client-test/build/src/test/java/com/basho/riak/client/core/RiakClientTest.java:[53,90] unchecked cast
  required: com.basho.riak.client.core.RiakFuture<java.lang.String,java.lang.String>
  found:    com.basho.riak.client.core.RiakFuture
```

**Comment by lukebakken** [comment]
What happens when you execute a long-running Riak command, but specify a short timeout? Does the client disregard the value when returned by Riak?

**Comment by alexmoore** [comment]
Yep, the command's execution will  [throw a TimeoutException()](https://github.com/basho/riak-java-client/blob/8918c5b01e554f79bedd5c853b76f0d881d07dda/src/main/java/com/basho/riak/client/core/FutureOperation.java#L342-L350), and unblock the user thread.  The operation will continue to process on Riak && the client's backend/netty threads until it completes in some fashion.

**Comment by lukebakken** [comment]
OK I just want to make sure that the data returned from Riak is discarded and not used somehow by a different command.

**Comment by lukebakken** [comment]
Other than my concern, :+1:

**Comment by alexmoore** [comment]
Nope, it should be discarded once the operation is complete, and the resources returned to the pool. It'll keep running in the background, but we'd need to add operation cancellation in to fix that (another issue).

**Pull request merged**
