### PR TITLE
Adds integration test verify inconsistent 2i query oageable reads

### PR DESCRIPTION
**Pull request by srgg**
WIP, DO NOT Merge this

### CODE REVIEW

**Comment by DSomogyi** [comment]
create jira issue

**Comment by alexmoore** [comment]
Hey Sergey, thanks for the test, it fails for me too.

This may be a Riak issue though, b/c I can replicate the bad query from the HTTP endpoint, it omits 7, 8, & 9 from the result set if you run the query immediately after the test is done. 

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqjtaaaaamsy

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqrtaaaaams0

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqltaaaaams5

The objects are created and do have the correct index entry set for them though:

``` bash
$ curl -XGET -v http://localhost:10018/buckets/2i-regression/keys/k7
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 10018 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 10018 (#0)
> GET /buckets/2i-regression/keys/k7 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:10018
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Riak-Vclock: a85hYGBgzGDKBVI8R4M2cpvbTdcCijzLYEpkzGNlsI1kP8+XBQA=
< x-riak-index-creationidx_int: 7
< Vary: Accept-Encoding
* Server MochiWeb/1.1 WebMachine/1.10.8 (that head fake, tho) is not blacklisted
< Server: MochiWeb/1.1 WebMachine/1.10.8 (that head fake, tho)
< Link: </buckets/2i-regression>; rel="up"
< Last-Modified: Tue, 30 Jun 2015 18:17:33 GMT
< ETag: "1r9SI1dG0tyYZBbZYWBbHW"
< Date: Tue, 30 Jun 2015 18:27:21 GMT
< Content-Type: application/octet-stream
< Content-Length: 1
<
* Connection #0 to host localhost left intact
7
```

**Comment by alexmoore** [comment]
Interesting, if I let it sit a few minutes, the results will change. The continuation returned by the 3rd page changes from `g2gCYQltAAAAAms5` to `g2gCYQZtAAAAAms2` :

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqrtaaaaams0_and_review_submitted_pr__jira__clients-503__by_srgg_ _pull_request__521_ _basho_riak-java-client

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqztaaaaams2_and_review_submitted_pr__jira__clients-503__by_srgg_ _pull_request__521_ _basho_riak-java-client

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqhtaaaaams4_and_review_submitted_pr__jira__clients-503__by_srgg_ _pull_request__521_ _basho_riak-java-client

localhost_10018_buckets_2i-regression_index_creationidx_int_0_10__max_results_2_return_terms_true_continuation_g2gcyqptaaaaa2sxma___and_review_submitted_pr__jira__clients-503__by_srgg_ _pull_request__521_ _basho_riak-java-client

**Comment by srgg** [comment]
Alex, I observe the same probabilistic behaviour as you posted above

**Comment by Basho-JIRA** [comment]
Bug is in Riak, not the clients. 

**_[posted via JIRA by Alexander Moore]**_

**Pull request closed without merging**
