### PR TITLE
Synch execute timeout [JIRA: CLIENTS-922]

### PR DESCRIPTION
**Pull request by bwittwer**
Ref Issue #609 (CLIENTS-818)

### CODE REVIEW

**Comment by alexmoore** [comment]
Hi @bwittwer,  

Thanks for the PR!  I'll see that this gets worked in soon.

--Alex

**Comment by alexmoore** [comment]
Hi @bwittwer,

Would it be possible to add a small test to this PR, testing the timeout?

Thanks,
Alex

**Comment by angrycub** [comment]
create jira issue

**Comment by lukebakken** [comment]
Incorporated into #642

**Pull request closed without merging**
