### PR TITLE
Not Ready: Updates to Java Client for Data Platform work.

### PR DESCRIPTION
**Pull request by alexmoore**

### CODE REVIEW

**Comment by alexmoore** [comment]
We still need the updates to riak_pb before we can merge & test.

**Comment by alexmoore** [comment]
As per @srgg, this is no longer needed.

**Comment by mdigan** [comment]
@alexmoore @srgg this PR was probably super stale, but we still need to get the parallel extract/coverage plan stuff merged at some point. Or is that in a different PR now?

**Comment by alexmoore** [comment]
@mdigan Good catch, we should do a new PR that's not so stale based on the latest merges that @srgg has done.

**Pull request closed without merging**
