### PR TITLE
Remove Support for Java 7

### LINKED ISSUE #635: Ending support for Java 7 [JIRA: CLIENTS-919]
Now that we are[ 1 year past the Java 7 End of Public Updates](http://www.oracle.com/technetwork/java/eol-135779.html), we should end support for it.  Moving to Java 8 will give us some nice code features too.

### PR DESCRIPTION
**Pull request by alexmoore**
Fixes #635 (CLIENTS-919).

### CODE REVIEW

**Comment by jplock** [comment]
Are you planning to use Stream's with this as well?  I've spotted a few places which could be converted to streams if needed.

**Comment by alexmoore** [comment]
@jplock I've certainly played with it, but I'm worried about performance.  I'll probably refactor those and do some A/B testing with our performance team to see if it has any noticeable effect.

**Comment by alexmoore** [comment]
@srgg When I add that 'maven-enforcer-plugin' into the code, `mvn install` fails with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.1:shade (default) on project riak-client: Error creating shaded jar: 18607 -> [Help 1]
```

Any idea what's going on there?

**Comment by alexmoore** [comment]
Replacing this PR with #666.

**Pull request closed without merging**
